version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app  # Mount local backend directory
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app  # Sync changes to container
    environment:
      - MONGO_URI=mongodb://mongo:27017/mlops-task3
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
    environment:
      - CHOKIDAR_USEPOLLING=true 
    depends_on:
      - backend

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    develop:
      watch:
        - action: sync
          path: ./redis-config  
          target: /usr/local/etc/redis

volumes:
  mongo-data:
